# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

#The Node.js orb contains a set of prepackaged CircleCI configurations
#you can use to easily install Node.js and its package managers (npm, yarn).
orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    executor: node/default # use the default executor defined within the orb
    working_directory: ../auctionapp_backed-master
    steps:
      - checkout #retrive the source code
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build app
          command: npm install --save
      - run:
          name: start server
          command: nodemon server.js
      - persist_to_workspace:
          root: ../auctionapp_backend-master
          paths: .

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  auction-backend-workflow:
    jobs:
      - build:
        context: ENV
